# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `grpc_reflection` gem.
# Please instead update this file by running `bin/tapioca gem grpc_reflection`.


# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:13
module Grpc; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:14
module Grpc::Reflection; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:15
module Grpc::Reflection::V1; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:23
class Grpc::Reflection::V1::ErrorResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:20
class Grpc::Reflection::V1::ExtensionNumberResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:17
class Grpc::Reflection::V1::ExtensionRequest < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:19
class Grpc::Reflection::V1::FileDescriptorResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:21
class Grpc::Reflection::V1::ListServiceResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_services_pb.rb:32
module Grpc::Reflection::V1::ServerReflection; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_services_pb.rb:33
class Grpc::Reflection::V1::ServerReflection::Service
  include ::GRPC::GenericService
  extend ::GRPC::GenericService::Dsl

  # pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_services_pb.rb:43
  def server_reflection_info(*_arg0); end
end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_services_pb.rb:46
class Grpc::Reflection::V1::ServerReflection::Stub < ::GRPC::ClientStub
  # pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_services_pb.rb:46
  def initialize(host, creds, **kw); end

  # pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_services_pb.rb:46
  def server_reflection_info(reqs, metadata = T.unsafe(nil), &blk); end
end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:16
class Grpc::Reflection::V1::ServerReflectionRequest < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:18
class Grpc::Reflection::V1::ServerReflectionResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1/reflection_pb.rb:22
class Grpc::Reflection::V1::ServiceResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_pb.rb:15
module Grpc::Reflection::V1alpha; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_pb.rb:23
class Grpc::Reflection::V1alpha::ErrorResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_pb.rb:20
class Grpc::Reflection::V1alpha::ExtensionNumberResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_pb.rb:17
class Grpc::Reflection::V1alpha::ExtensionRequest < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_pb.rb:19
class Grpc::Reflection::V1alpha::FileDescriptorResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_pb.rb:21
class Grpc::Reflection::V1alpha::ListServiceResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_services_pb.rb:27
module Grpc::Reflection::V1alpha::ServerReflection; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_services_pb.rb:28
class Grpc::Reflection::V1alpha::ServerReflection::Service
  include ::GRPC::GenericService
  extend ::GRPC::GenericService::Dsl

  # pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_services_pb.rb:38
  def server_reflection_info(*_arg0); end
end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_services_pb.rb:41
class Grpc::Reflection::V1alpha::ServerReflection::Stub < ::GRPC::ClientStub
  # pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_services_pb.rb:41
  def initialize(host, creds, **kw); end

  # pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_services_pb.rb:41
  def server_reflection_info(reqs, metadata = T.unsafe(nil), &blk); end
end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_pb.rb:16
class Grpc::Reflection::V1alpha::ServerReflectionRequest < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_pb.rb:18
class Grpc::Reflection::V1alpha::ServerReflectionResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/reflection/v1alpha/reflection_v1alpha_pb.rb:22
class Grpc::Reflection::V1alpha::ServiceResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/version.rb:3
module GrpcReflection; end

# pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_decorator.rb:8
class GrpcReflection::FileDescriptorDecorator
  # pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_decorator.rb:11
  def initialize(file_descriptor_proto); end

  # pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_decorator.rb:9
  def dataset; end

  # pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_decorator.rb:9
  def dependency; end

  # pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_decorator.rb:9
  def filename; end

  # pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_decorator.rb:9
  def serialized_file; end

  private

  # pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_decorator.rb:24
  def set_dataset; end
end

# pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_manager.rb:4
module GrpcReflection::FileDescriptorManager
  class << self
    # pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_manager.rb:8
    def add(file_descriptor_proto); end

    # pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_manager.rb:14
    def find(name); end

    private

    # pkg:gem/grpc_reflection#lib/grpc_reflection/file_descriptor_manager.rb:39
    def find_file_descriptor(name); end
  end
end

# pkg:gem/grpc_reflection#lib/grpc_reflection/server.rb:5
class GrpcReflection::Server < ::Grpc::Reflection::V1::ServerReflection::Service
  include ::GrpcReflection::ServerShared

  # pkg:gem/grpc_reflection#lib/grpc_reflection/server.rb:8
  def server_reflection_info(req, _unused_call); end
end

# pkg:gem/grpc_reflection#lib/grpc_reflection/server_alpha.rb:5
class GrpcReflection::ServerAlpha < ::Grpc::Reflection::V1alpha::ServerReflection::Service
  include ::GrpcReflection::ServerShared

  # pkg:gem/grpc_reflection#lib/grpc_reflection/server_alpha.rb:8
  def server_reflection_info(req, _unused_call); end
end

# pkg:gem/grpc_reflection#lib/grpc_reflection/server_shared.rb:2
module GrpcReflection::ServerShared
  # pkg:gem/grpc_reflection#lib/grpc_reflection/server_shared.rb:3
  def server_reflection_info_response(req, proto_module); end

  private

  # pkg:gem/grpc_reflection#lib/grpc_reflection/server_shared.rb:43
  def list_services_response(proto_module); end

  # pkg:gem/grpc_reflection#lib/grpc_reflection/server_shared.rb:35
  def main_server; end

  # pkg:gem/grpc_reflection#lib/grpc_reflection/server_shared.rb:39
  def service_names; end
end

# pkg:gem/grpc_reflection#lib/grpc_reflection/version.rb:4
GrpcReflection::VERSION = T.let(T.unsafe(nil), String)
