# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `kinetix-contracts` gem.
# Please instead update this file by running `bin/tapioca gem kinetix-contracts`.


# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:13
module Identity; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:14
module Identity::V1; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:22
class Identity::V1::GetMerchantInfoRequest < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:23
class Identity::V1::GetMerchantInfoResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:18
class Identity::V1::GetPrincipalRequest < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:19
class Identity::V1::GetPrincipalResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:20
class Identity::V1::GetUserProfileRequest < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:21
class Identity::V1::GetUserProfileResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:9
module Identity::V1::IdentityService; end

# pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:10
class Identity::V1::IdentityService::Service
  include ::GRPC::GenericService
  extend ::GRPC::GenericService::Dsl

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:21
  def get_merchant_info(*_arg0); end

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:19
  def get_principal(*_arg0); end

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:20
  def get_user_profile(*_arg0); end

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:18
  def resolve_principal(*_arg0); end

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:22
  def validate_token(*_arg0); end
end

# pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:25
class Identity::V1::IdentityService::Stub < ::GRPC::ClientStub
  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:25
  def initialize(host, creds, **kw); end

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:25
  def get_merchant_info(req, metadata = T.unsafe(nil)); end

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:25
  def get_principal(req, metadata = T.unsafe(nil)); end

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:25
  def get_user_profile(req, metadata = T.unsafe(nil)); end

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:25
  def resolve_principal(req, metadata = T.unsafe(nil)); end

  # pkg:gem/kinetix-contracts#identity/v1/identity_services_pb.rb:25
  def validate_token(req, metadata = T.unsafe(nil)); end
end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:27
module Identity::V1::MerchantStatus
  class << self
    # pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:27
    def descriptor; end

    # pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:27
    def lookup(_arg0); end

    # pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:27
    def resolve(_arg0); end
  end
end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:27
Identity::V1::MerchantStatus::MERCHANT_STATUS_CLOSED = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:27
Identity::V1::MerchantStatus::MERCHANT_STATUS_PENDING = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:27
Identity::V1::MerchantStatus::MERCHANT_STATUS_SUSPENDED = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:27
Identity::V1::MerchantStatus::MERCHANT_STATUS_UNSPECIFIED = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:27
Identity::V1::MerchantStatus::MERCHANT_STATUS_VERIFIED = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
module Identity::V1::PrincipalKind
  class << self
    # pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
    def descriptor; end

    # pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
    def lookup(_arg0); end

    # pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
    def resolve(_arg0); end
  end
end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
Identity::V1::PrincipalKind::PRINCIPAL_KIND_CUSTOMER = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
Identity::V1::PrincipalKind::PRINCIPAL_KIND_DRIVER = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
Identity::V1::PrincipalKind::PRINCIPAL_KIND_MERCHANT = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
Identity::V1::PrincipalKind::PRINCIPAL_KIND_SERVICE = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
Identity::V1::PrincipalKind::PRINCIPAL_KIND_STAFF = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:26
Identity::V1::PrincipalKind::PRINCIPAL_KIND_UNSPECIFIED = T.let(T.unsafe(nil), Integer)

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:16
class Identity::V1::ResolvePrincipalRequest < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:17
class Identity::V1::ResolvePrincipalResponse < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:15
class Identity::V1::ServiceLocalId < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:24
class Identity::V1::ValidateTokenRequest < ::Google::Protobuf::AbstractMessage; end

# pkg:gem/kinetix-contracts#identity/v1/identity_pb.rb:25
class Identity::V1::ValidateTokenResponse < ::Google::Protobuf::AbstractMessage; end
