# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grpc::Health::V1::HealthCheckRequest`.
# Please instead update this file by running `bin/tapioca dsl Grpc::Health::V1::HealthCheckRequest`.


class Grpc::Health::V1::HealthCheckRequest < Google::Protobuf::AbstractMessage
  sig { params(service: T.nilable(String)).void }
  def initialize(service: nil); end

  sig { void }
  def clear_service; end

  sig { returns(String) }
  def service; end

  sig { params(value: String).void }
  def service=(value); end
end
