# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Common::V1::Address`.
# Please instead update this file by running `bin/tapioca dsl Common::V1::Address`.


class Common::V1::Address < Google::Protobuf::AbstractMessage
  sig do
    params(
      city: T.nilable(String),
      location: T.nilable(Common::V1::GeoPoint),
      phone_number: T.nilable(String),
      postal_code: T.nilable(String),
      recipient_name: T.nilable(String),
      street_address: T.nilable(String)
    ).void
  end
  def initialize(city: nil, location: nil, phone_number: nil, postal_code: nil, recipient_name: nil, street_address: nil); end

  sig { returns(String) }
  def city; end

  sig { params(value: String).void }
  def city=(value); end

  sig { void }
  def clear_city; end

  sig { void }
  def clear_location; end

  sig { void }
  def clear_phone_number; end

  sig { void }
  def clear_postal_code; end

  sig { void }
  def clear_recipient_name; end

  sig { void }
  def clear_street_address; end

  sig { returns(Object) }
  def has_location?; end

  sig { returns(T.nilable(Common::V1::GeoPoint)) }
  def location; end

  sig { params(value: T.nilable(Common::V1::GeoPoint)).void }
  def location=(value); end

  sig { returns(String) }
  def phone_number; end

  sig { params(value: String).void }
  def phone_number=(value); end

  sig { returns(String) }
  def postal_code; end

  sig { params(value: String).void }
  def postal_code=(value); end

  sig { returns(String) }
  def recipient_name; end

  sig { params(value: String).void }
  def recipient_name=(value); end

  sig { returns(String) }
  def street_address; end

  sig { params(value: String).void }
  def street_address=(value); end
end
