# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Common::V1::CourierStatus`.
# Please instead update this file by running `bin/tapioca dsl Common::V1::CourierStatus`.


module Common::V1::CourierStatus
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Common::V1::CourierStatus::COURIER_STATUS_ASSIGNED = 2
Common::V1::CourierStatus::COURIER_STATUS_COMPLETED = 6
Common::V1::CourierStatus::COURIER_STATUS_EN_ROUTE_DELIVERY = 5
Common::V1::CourierStatus::COURIER_STATUS_EN_ROUTE_PICKUP = 3
Common::V1::CourierStatus::COURIER_STATUS_IDLE = 1
Common::V1::CourierStatus::COURIER_STATUS_PICKED_UP = 4
Common::V1::CourierStatus::COURIER_STATUS_UNSPECIFIED = 0
