# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Common::V1::ErrorDetail`.
# Please instead update this file by running `bin/tapioca dsl Common::V1::ErrorDetail`.


class Common::V1::ErrorDetail < Google::Protobuf::AbstractMessage
  sig do
    params(
      error_code: T.nilable(String),
      field_violations: T.nilable(T::Array[String]),
      message: T.nilable(String)
    ).void
  end
  def initialize(error_code: nil, field_violations: T.unsafe(nil), message: nil); end

  sig { void }
  def clear_error_code; end

  sig { void }
  def clear_field_violations; end

  sig { void }
  def clear_message; end

  sig { returns(String) }
  def error_code; end

  sig { params(value: String).void }
  def error_code=(value); end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def field_violations; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def field_violations=(value); end

  sig { returns(String) }
  def message; end

  sig { params(value: String).void }
  def message=(value); end
end
