# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Common::V1::GeoPoint`.
# Please instead update this file by running `bin/tapioca dsl Common::V1::GeoPoint`.


class Common::V1::GeoPoint < Google::Protobuf::AbstractMessage
  sig { params(latitude: T.nilable(Float), longitude: T.nilable(Float)).void }
  def initialize(latitude: nil, longitude: nil); end

  sig { void }
  def clear_latitude; end

  sig { void }
  def clear_longitude; end

  sig { returns(Float) }
  def latitude; end

  sig { params(value: Float).void }
  def latitude=(value); end

  sig { returns(Float) }
  def longitude; end

  sig { params(value: Float).void }
  def longitude=(value); end
end
