# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Common::V1::Money`.
# Please instead update this file by running `bin/tapioca dsl Common::V1::Money`.


class Common::V1::Money < Google::Protobuf::AbstractMessage
  sig { params(amount_minor: T.nilable(Integer), currency: T.nilable(String)).void }
  def initialize(amount_minor: nil, currency: nil); end

  sig { returns(Integer) }
  def amount_minor; end

  sig { params(value: Integer).void }
  def amount_minor=(value); end

  sig { void }
  def clear_amount_minor; end

  sig { void }
  def clear_currency; end

  sig { returns(String) }
  def currency; end

  sig { params(value: String).void }
  def currency=(value); end
end
