# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Common::V1::OrderItem`.
# Please instead update this file by running `bin/tapioca dsl Common::V1::OrderItem`.


class Common::V1::OrderItem < Google::Protobuf::AbstractMessage
  sig do
    params(
      bin_location: T.nilable(String),
      product_name: T.nilable(String),
      quantity: T.nilable(Integer),
      sku: T.nilable(String),
      unit_price: T.nilable(Common::V1::Money)
    ).void
  end
  def initialize(bin_location: nil, product_name: nil, quantity: nil, sku: nil, unit_price: nil); end

  sig { returns(String) }
  def bin_location; end

  sig { params(value: String).void }
  def bin_location=(value); end

  sig { void }
  def clear_bin_location; end

  sig { void }
  def clear_product_name; end

  sig { void }
  def clear_quantity; end

  sig { void }
  def clear_sku; end

  sig { void }
  def clear_unit_price; end

  sig { returns(Object) }
  def has_unit_price?; end

  sig { returns(String) }
  def product_name; end

  sig { params(value: String).void }
  def product_name=(value); end

  sig { returns(Integer) }
  def quantity; end

  sig { params(value: Integer).void }
  def quantity=(value); end

  sig { returns(String) }
  def sku; end

  sig { params(value: String).void }
  def sku=(value); end

  sig { returns(T.nilable(Common::V1::Money)) }
  def unit_price; end

  sig { params(value: T.nilable(Common::V1::Money)).void }
  def unit_price=(value); end
end
