# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Common::V1::OrderStatus`.
# Please instead update this file by running `bin/tapioca dsl Common::V1::OrderStatus`.


module Common::V1::OrderStatus
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Common::V1::OrderStatus::ORDER_STATUS_ASSIGNED = 6
Common::V1::OrderStatus::ORDER_STATUS_CANCELLED = 11
Common::V1::OrderStatus::ORDER_STATUS_COMPLETED = 10
Common::V1::OrderStatus::ORDER_STATUS_DELIVERED = 9
Common::V1::OrderStatus::ORDER_STATUS_DISPATCHED = 7
Common::V1::OrderStatus::ORDER_STATUS_IN_TRANSIT = 8
Common::V1::OrderStatus::ORDER_STATUS_PACKED = 5
Common::V1::OrderStatus::ORDER_STATUS_PACKING = 4
Common::V1::OrderStatus::ORDER_STATUS_PAID = 2
Common::V1::OrderStatus::ORDER_STATUS_PENDING_PAYMENT = 1
Common::V1::OrderStatus::ORDER_STATUS_RECEIVED = 3
Common::V1::OrderStatus::ORDER_STATUS_REFUNDED = 12
Common::V1::OrderStatus::ORDER_STATUS_UNSPECIFIED = 0
