# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Common::V1::ReturnStatus`.
# Please instead update this file by running `bin/tapioca dsl Common::V1::ReturnStatus`.


module Common::V1::ReturnStatus
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Common::V1::ReturnStatus::RETURN_STATUS_INSPECTED = 4
Common::V1::ReturnStatus::RETURN_STATUS_PICKED_UP_FROM_BUYER = 2
Common::V1::ReturnStatus::RETURN_STATUS_RECEIVED_AT_WAREHOUSE = 3
Common::V1::ReturnStatus::RETURN_STATUS_REJECTED = 6
Common::V1::ReturnStatus::RETURN_STATUS_REQUESTED = 1
Common::V1::ReturnStatus::RETURN_STATUS_RESOLVED = 5
Common::V1::ReturnStatus::RETURN_STATUS_UNSPECIFIED = 0
