# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::FeatureSet::VisibilityFeature::DefaultSymbolVisibility`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::FeatureSet::VisibilityFeature::DefaultSymbolVisibility`.


module Google::Protobuf::FeatureSet::VisibilityFeature::DefaultSymbolVisibility
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Google::Protobuf::FeatureSet::VisibilityFeature::DefaultSymbolVisibility::DEFAULT_SYMBOL_VISIBILITY_UNKNOWN = 0
Google::Protobuf::FeatureSet::VisibilityFeature::DefaultSymbolVisibility::EXPORT_ALL = 1
Google::Protobuf::FeatureSet::VisibilityFeature::DefaultSymbolVisibility::EXPORT_TOP_LEVEL = 2
Google::Protobuf::FeatureSet::VisibilityFeature::DefaultSymbolVisibility::LOCAL_ALL = 3
Google::Protobuf::FeatureSet::VisibilityFeature::DefaultSymbolVisibility::STRICT = 4
