# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grpc::Reflection::V1alpha::ErrorResponse`.
# Please instead update this file by running `bin/tapioca dsl Grpc::Reflection::V1alpha::ErrorResponse`.


class Grpc::Reflection::V1alpha::ErrorResponse < Google::Protobuf::AbstractMessage
  sig { params(error_code: T.nilable(Integer), error_message: T.nilable(String)).void }
  def initialize(error_code: nil, error_message: nil); end

  sig { void }
  def clear_error_code; end

  sig { void }
  def clear_error_message; end

  sig { returns(Integer) }
  def error_code; end

  sig { params(value: Integer).void }
  def error_code=(value); end

  sig { returns(String) }
  def error_message; end

  sig { params(value: String).void }
  def error_message=(value); end
end
