# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grpc::Reflection::V1alpha::ListServiceResponse`.
# Please instead update this file by running `bin/tapioca dsl Grpc::Reflection::V1alpha::ListServiceResponse`.


class Grpc::Reflection::V1alpha::ListServiceResponse < Google::Protobuf::AbstractMessage
  sig { params(service: T.nilable(T::Array[Grpc::Reflection::V1alpha::ServiceResponse])).void }
  def initialize(service: T.unsafe(nil)); end

  sig { void }
  def clear_service; end

  sig { returns(Google::Protobuf::RepeatedField[Grpc::Reflection::V1alpha::ServiceResponse]) }
  def service; end

  sig { params(value: Google::Protobuf::RepeatedField[Grpc::Reflection::V1alpha::ServiceResponse]).void }
  def service=(value); end
end
