# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grpc::Reflection::V1alpha::ServerReflectionRequest`.
# Please instead update this file by running `bin/tapioca dsl Grpc::Reflection::V1alpha::ServerReflectionRequest`.


class Grpc::Reflection::V1alpha::ServerReflectionRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      all_extension_numbers_of_type: T.nilable(String),
      file_by_filename: T.nilable(String),
      file_containing_extension: T.nilable(Grpc::Reflection::V1alpha::ExtensionRequest),
      file_containing_symbol: T.nilable(String),
      host: T.nilable(String),
      list_services: T.nilable(String)
    ).void
  end
  def initialize(all_extension_numbers_of_type: nil, file_by_filename: nil, file_containing_extension: nil, file_containing_symbol: nil, host: nil, list_services: nil); end

  sig { returns(String) }
  def all_extension_numbers_of_type; end

  sig { params(value: String).void }
  def all_extension_numbers_of_type=(value); end

  sig { void }
  def clear_all_extension_numbers_of_type; end

  sig { void }
  def clear_file_by_filename; end

  sig { void }
  def clear_file_containing_extension; end

  sig { void }
  def clear_file_containing_symbol; end

  sig { void }
  def clear_host; end

  sig { void }
  def clear_list_services; end

  sig { returns(String) }
  def file_by_filename; end

  sig { params(value: String).void }
  def file_by_filename=(value); end

  sig { returns(T.nilable(Grpc::Reflection::V1alpha::ExtensionRequest)) }
  def file_containing_extension; end

  sig { params(value: T.nilable(Grpc::Reflection::V1alpha::ExtensionRequest)).void }
  def file_containing_extension=(value); end

  sig { returns(String) }
  def file_containing_symbol; end

  sig { params(value: String).void }
  def file_containing_symbol=(value); end

  sig { returns(Object) }
  def has_all_extension_numbers_of_type?; end

  sig { returns(Object) }
  def has_file_by_filename?; end

  sig { returns(Object) }
  def has_file_containing_extension?; end

  sig { returns(Object) }
  def has_file_containing_symbol?; end

  sig { returns(Object) }
  def has_list_services?; end

  sig { returns(String) }
  def host; end

  sig { params(value: String).void }
  def host=(value); end

  sig { returns(String) }
  def list_services; end

  sig { params(value: String).void }
  def list_services=(value); end

  sig { returns(T.nilable(Symbol)) }
  def message_request; end
end
