# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grpc::Reflection::V1alpha::ServerReflectionResponse`.
# Please instead update this file by running `bin/tapioca dsl Grpc::Reflection::V1alpha::ServerReflectionResponse`.


class Grpc::Reflection::V1alpha::ServerReflectionResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      all_extension_numbers_response: T.nilable(Grpc::Reflection::V1alpha::ExtensionNumberResponse),
      error_response: T.nilable(Grpc::Reflection::V1alpha::ErrorResponse),
      file_descriptor_response: T.nilable(Grpc::Reflection::V1alpha::FileDescriptorResponse),
      list_services_response: T.nilable(Grpc::Reflection::V1alpha::ListServiceResponse),
      original_request: T.nilable(Grpc::Reflection::V1alpha::ServerReflectionRequest),
      valid_host: T.nilable(String)
    ).void
  end
  def initialize(all_extension_numbers_response: nil, error_response: nil, file_descriptor_response: nil, list_services_response: nil, original_request: nil, valid_host: nil); end

  sig { returns(T.nilable(Grpc::Reflection::V1alpha::ExtensionNumberResponse)) }
  def all_extension_numbers_response; end

  sig { params(value: T.nilable(Grpc::Reflection::V1alpha::ExtensionNumberResponse)).void }
  def all_extension_numbers_response=(value); end

  sig { void }
  def clear_all_extension_numbers_response; end

  sig { void }
  def clear_error_response; end

  sig { void }
  def clear_file_descriptor_response; end

  sig { void }
  def clear_list_services_response; end

  sig { void }
  def clear_original_request; end

  sig { void }
  def clear_valid_host; end

  sig { returns(T.nilable(Grpc::Reflection::V1alpha::ErrorResponse)) }
  def error_response; end

  sig { params(value: T.nilable(Grpc::Reflection::V1alpha::ErrorResponse)).void }
  def error_response=(value); end

  sig { returns(T.nilable(Grpc::Reflection::V1alpha::FileDescriptorResponse)) }
  def file_descriptor_response; end

  sig { params(value: T.nilable(Grpc::Reflection::V1alpha::FileDescriptorResponse)).void }
  def file_descriptor_response=(value); end

  sig { returns(Object) }
  def has_all_extension_numbers_response?; end

  sig { returns(Object) }
  def has_error_response?; end

  sig { returns(Object) }
  def has_file_descriptor_response?; end

  sig { returns(Object) }
  def has_list_services_response?; end

  sig { returns(Object) }
  def has_original_request?; end

  sig { returns(T.nilable(Grpc::Reflection::V1alpha::ListServiceResponse)) }
  def list_services_response; end

  sig { params(value: T.nilable(Grpc::Reflection::V1alpha::ListServiceResponse)).void }
  def list_services_response=(value); end

  sig { returns(T.nilable(Symbol)) }
  def message_response; end

  sig { returns(T.nilable(Grpc::Reflection::V1alpha::ServerReflectionRequest)) }
  def original_request; end

  sig { params(value: T.nilable(Grpc::Reflection::V1alpha::ServerReflectionRequest)).void }
  def original_request=(value); end

  sig { returns(String) }
  def valid_host; end

  sig { params(value: String).void }
  def valid_host=(value); end
end
