# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::FeatureSet`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::FeatureSet`.


class Google::Protobuf::FeatureSet < Google::Protobuf::AbstractMessage
  sig do
    params(
      default_symbol_visibility: T.nilable(T.any(Symbol, Integer)),
      enforce_naming_style: T.nilable(T.any(Symbol, Integer)),
      enforce_proto_limits: T.nilable(T.any(Symbol, Integer)),
      enum_type: T.nilable(T.any(Symbol, Integer)),
      field_presence: T.nilable(T.any(Symbol, Integer)),
      json_format: T.nilable(T.any(Symbol, Integer)),
      message_encoding: T.nilable(T.any(Symbol, Integer)),
      repeated_field_encoding: T.nilable(T.any(Symbol, Integer)),
      utf8_validation: T.nilable(T.any(Symbol, Integer))
    ).void
  end
  def initialize(default_symbol_visibility: nil, enforce_naming_style: nil, enforce_proto_limits: nil, enum_type: nil, field_presence: nil, json_format: nil, message_encoding: nil, repeated_field_encoding: nil, utf8_validation: nil); end

  sig { void }
  def clear_default_symbol_visibility; end

  sig { void }
  def clear_enforce_naming_style; end

  sig { void }
  def clear_enforce_proto_limits; end

  sig { void }
  def clear_enum_type; end

  sig { void }
  def clear_field_presence; end

  sig { void }
  def clear_json_format; end

  sig { void }
  def clear_message_encoding; end

  sig { void }
  def clear_repeated_field_encoding; end

  sig { void }
  def clear_utf8_validation; end

  sig { returns(T.any(Symbol, Integer)) }
  def default_symbol_visibility; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def default_symbol_visibility=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def enforce_naming_style; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def enforce_naming_style=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def enforce_proto_limits; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def enforce_proto_limits=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def enum_type; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def enum_type=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def field_presence; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def field_presence=(value); end

  sig { returns(Object) }
  def has_default_symbol_visibility?; end

  sig { returns(Object) }
  def has_enforce_naming_style?; end

  sig { returns(Object) }
  def has_enforce_proto_limits?; end

  sig { returns(Object) }
  def has_enum_type?; end

  sig { returns(Object) }
  def has_field_presence?; end

  sig { returns(Object) }
  def has_json_format?; end

  sig { returns(Object) }
  def has_message_encoding?; end

  sig { returns(Object) }
  def has_repeated_field_encoding?; end

  sig { returns(Object) }
  def has_utf8_validation?; end

  sig { returns(T.any(Symbol, Integer)) }
  def json_format; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def json_format=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def message_encoding; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def message_encoding=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def repeated_field_encoding; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def repeated_field_encoding=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def utf8_validation; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def utf8_validation=(value); end
end
