# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::FileDescriptorSet`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::FileDescriptorSet`.


class Google::Protobuf::FileDescriptorSet < Google::Protobuf::AbstractMessage
  sig { params(file: T.nilable(T::Array[Google::Protobuf::FileDescriptorProto])).void }
  def initialize(file: T.unsafe(nil)); end

  sig { void }
  def clear_file; end

  sig { returns(Google::Protobuf::RepeatedField[Google::Protobuf::FileDescriptorProto]) }
  def file; end

  sig { params(value: Google::Protobuf::RepeatedField[Google::Protobuf::FileDescriptorProto]).void }
  def file=(value); end
end
