# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::SymbolVisibility`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::SymbolVisibility`.


module Google::Protobuf::SymbolVisibility
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Google::Protobuf::SymbolVisibility::VISIBILITY_EXPORT = 2
Google::Protobuf::SymbolVisibility::VISIBILITY_LOCAL = 1
Google::Protobuf::SymbolVisibility::VISIBILITY_UNSET = 0
