# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CancelOrderRequest`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CancelOrderRequest`.


class Fulfillment::V1::CancelOrderRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      idempotency_key: T.nilable(Common::V1::IdempotencyKey),
      merchant_principal_id: T.nilable(String),
      order_id: T.nilable(String),
      reason: T.nilable(String)
    ).void
  end
  def initialize(idempotency_key: nil, merchant_principal_id: nil, order_id: nil, reason: nil); end

  sig { void }
  def clear_idempotency_key; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_id; end

  sig { void }
  def clear_reason; end

  sig { returns(Object) }
  def has_idempotency_key?; end

  sig { returns(T.nilable(Common::V1::IdempotencyKey)) }
  def idempotency_key; end

  sig { params(value: T.nilable(Common::V1::IdempotencyKey)).void }
  def idempotency_key=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_id; end

  sig { params(value: String).void }
  def order_id=(value); end

  sig { returns(String) }
  def reason; end

  sig { params(value: String).void }
  def reason=(value); end
end
