# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CancelFulfillmentTaskRequest`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CancelFulfillmentTaskRequest`.


class Fulfillment::V1::CancelFulfillmentTaskRequest < Google::Protobuf::AbstractMessage
  sig { params(merchant_principal_id: T.nilable(String), reason: T.nilable(String), task_id: T.nilable(String)).void }
  def initialize(merchant_principal_id: nil, reason: nil, task_id: nil); end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_reason; end

  sig { void }
  def clear_task_id; end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def reason; end

  sig { params(value: String).void }
  def reason=(value); end

  sig { returns(String) }
  def task_id; end

  sig { params(value: String).void }
  def task_id=(value); end
end
