# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CancelOrderResponse`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CancelOrderResponse`.


class Fulfillment::V1::CancelOrderResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      current_status: T.nilable(T.any(Symbol, Integer)),
      message: T.nilable(String),
      success: T.nilable(T::Boolean)
    ).void
  end
  def initialize(current_status: nil, message: nil, success: nil); end

  sig { void }
  def clear_current_status; end

  sig { void }
  def clear_message; end

  sig { void }
  def clear_success; end

  sig { returns(T.any(Symbol, Integer)) }
  def current_status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def current_status=(value); end

  sig { returns(String) }
  def message; end

  sig { params(value: String).void }
  def message=(value); end

  sig { returns(T::Boolean) }
  def success; end

  sig { params(value: T::Boolean).void }
  def success=(value); end
end
