# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CancelFulfillmentTaskResponse`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CancelFulfillmentTaskResponse`.


class Fulfillment::V1::CancelFulfillmentTaskResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      already_cancelled: T.nilable(T::Boolean),
      error: T.nilable(Common::V1::ErrorDetail),
      success: T.nilable(T::Boolean)
    ).void
  end
  def initialize(already_cancelled: nil, error: nil, success: nil); end

  sig { returns(T::Boolean) }
  def already_cancelled; end

  sig { params(value: T::Boolean).void }
  def already_cancelled=(value); end

  sig { void }
  def clear_already_cancelled; end

  sig { void }
  def clear_error; end

  sig { void }
  def clear_success; end

  sig { returns(T.nilable(Common::V1::ErrorDetail)) }
  def error; end

  sig { params(value: T.nilable(Common::V1::ErrorDetail)).void }
  def error=(value); end

  sig { returns(Object) }
  def has_error?; end

  sig { returns(T::Boolean) }
  def success; end

  sig { params(value: T::Boolean).void }
  def success=(value); end
end
