# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CheckBinStockBatchResponse`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CheckBinStockBatchResponse`.


class Fulfillment::V1::CheckBinStockBatchResponse < Google::Protobuf::AbstractMessage
  sig { params(items: T.nilable(T::Array[Fulfillment::V1::CheckBinStockResponse])).void }
  def initialize(items: T.unsafe(nil)); end

  sig { void }
  def clear_items; end

  sig { returns(Google::Protobuf::RepeatedField[Fulfillment::V1::CheckBinStockResponse]) }
  def items; end

  sig { params(value: Google::Protobuf::RepeatedField[Fulfillment::V1::CheckBinStockResponse]).void }
  def items=(value); end
end
