# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CheckBinStockBatchRequest`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CheckBinStockBatchRequest`.


class Fulfillment::V1::CheckBinStockBatchRequest < Google::Protobuf::AbstractMessage
  sig { params(merchant_principal_id: T.nilable(String), skus: T.nilable(T::Array[String])).void }
  def initialize(merchant_principal_id: nil, skus: T.unsafe(nil)); end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_skus; end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def skus; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def skus=(value); end
end
