# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CheckBinStockResponse`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CheckBinStockResponse`.


class Fulfillment::V1::CheckBinStockResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      allocated_stock: T.nilable(Integer),
      available_stock: T.nilable(Integer),
      bin_location: T.nilable(String),
      found: T.nilable(T::Boolean),
      low_stock_warning: T.nilable(T::Boolean),
      physical_stock: T.nilable(Integer),
      product_name: T.nilable(String),
      sku: T.nilable(String)
    ).void
  end
  def initialize(allocated_stock: nil, available_stock: nil, bin_location: nil, found: nil, low_stock_warning: nil, physical_stock: nil, product_name: nil, sku: nil); end

  sig { returns(Integer) }
  def allocated_stock; end

  sig { params(value: Integer).void }
  def allocated_stock=(value); end

  sig { returns(Integer) }
  def available_stock; end

  sig { params(value: Integer).void }
  def available_stock=(value); end

  sig { returns(String) }
  def bin_location; end

  sig { params(value: String).void }
  def bin_location=(value); end

  sig { void }
  def clear_allocated_stock; end

  sig { void }
  def clear_available_stock; end

  sig { void }
  def clear_bin_location; end

  sig { void }
  def clear_found; end

  sig { void }
  def clear_low_stock_warning; end

  sig { void }
  def clear_physical_stock; end

  sig { void }
  def clear_product_name; end

  sig { void }
  def clear_sku; end

  sig { returns(T::Boolean) }
  def found; end

  sig { params(value: T::Boolean).void }
  def found=(value); end

  sig { returns(T::Boolean) }
  def low_stock_warning; end

  sig { params(value: T::Boolean).void }
  def low_stock_warning=(value); end

  sig { returns(Integer) }
  def physical_stock; end

  sig { params(value: Integer).void }
  def physical_stock=(value); end

  sig { returns(String) }
  def product_name; end

  sig { params(value: String).void }
  def product_name=(value); end

  sig { returns(String) }
  def sku; end

  sig { params(value: String).void }
  def sku=(value); end
end
