# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CheckBinStockRequest`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CheckBinStockRequest`.


class Fulfillment::V1::CheckBinStockRequest < Google::Protobuf::AbstractMessage
  sig { params(merchant_principal_id: T.nilable(String), sku: T.nilable(String)).void }
  def initialize(merchant_principal_id: nil, sku: nil); end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_sku; end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def sku; end

  sig { params(value: String).void }
  def sku=(value); end
end
