# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CreateOrderResponse`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CreateOrderResponse`.


class Fulfillment::V1::CreateOrderResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      created_at: T.nilable(Google::Protobuf::Timestamp),
      error: T.nilable(Common::V1::ErrorDetail),
      merchant_principal_id: T.nilable(String),
      order_id: T.nilable(String),
      order_number: T.nilable(String),
      status: T.nilable(T.any(Symbol, Integer)),
      success: T.nilable(T::Boolean)
    ).void
  end
  def initialize(created_at: nil, error: nil, merchant_principal_id: nil, order_id: nil, order_number: nil, status: nil, success: nil); end

  sig { void }
  def clear_created_at; end

  sig { void }
  def clear_error; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_id; end

  sig { void }
  def clear_order_number; end

  sig { void }
  def clear_status; end

  sig { void }
  def clear_success; end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def created_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def created_at=(value); end

  sig { returns(T.nilable(Common::V1::ErrorDetail)) }
  def error; end

  sig { params(value: T.nilable(Common::V1::ErrorDetail)).void }
  def error=(value); end

  sig { returns(Object) }
  def has_created_at?; end

  sig { returns(Object) }
  def has_error?; end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_id; end

  sig { params(value: String).void }
  def order_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end

  sig { returns(T::Boolean) }
  def success; end

  sig { params(value: T::Boolean).void }
  def success=(value); end
end
