# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CreateFulfillmentTaskResponse`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CreateFulfillmentTaskResponse`.


class Fulfillment::V1::CreateFulfillmentTaskResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      already_created: T.nilable(T::Boolean),
      error: T.nilable(Common::V1::ErrorDetail),
      success: T.nilable(T::Boolean),
      task_id: T.nilable(String)
    ).void
  end
  def initialize(already_created: nil, error: nil, success: nil, task_id: nil); end

  sig { returns(T::Boolean) }
  def already_created; end

  sig { params(value: T::Boolean).void }
  def already_created=(value); end

  sig { void }
  def clear_already_created; end

  sig { void }
  def clear_error; end

  sig { void }
  def clear_success; end

  sig { void }
  def clear_task_id; end

  sig { returns(T.nilable(Common::V1::ErrorDetail)) }
  def error; end

  sig { params(value: T.nilable(Common::V1::ErrorDetail)).void }
  def error=(value); end

  sig { returns(Object) }
  def has_error?; end

  sig { returns(T::Boolean) }
  def success; end

  sig { params(value: T::Boolean).void }
  def success=(value); end

  sig { returns(String) }
  def task_id; end

  sig { params(value: String).void }
  def task_id=(value); end
end
