# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CreateFulfillmentTaskRequest`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CreateFulfillmentTaskRequest`.


class Fulfillment::V1::CreateFulfillmentTaskRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      idempotency_key: T.nilable(Common::V1::IdempotencyKey),
      lines: T.nilable(T::Array[Fulfillment::V1::FulfillmentTaskLine]),
      merchant_principal_id: T.nilable(String),
      order_number: T.nilable(String)
    ).void
  end
  def initialize(idempotency_key: nil, lines: T.unsafe(nil), merchant_principal_id: nil, order_number: nil); end

  sig { void }
  def clear_idempotency_key; end

  sig { void }
  def clear_lines; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_number; end

  sig { returns(Object) }
  def has_idempotency_key?; end

  sig { returns(T.nilable(Common::V1::IdempotencyKey)) }
  def idempotency_key; end

  sig { params(value: T.nilable(Common::V1::IdempotencyKey)).void }
  def idempotency_key=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Fulfillment::V1::FulfillmentTaskLine]) }
  def lines; end

  sig { params(value: Google::Protobuf::RepeatedField[Fulfillment::V1::FulfillmentTaskLine]).void }
  def lines=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end
end
