# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::CreateOrderRequest`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::CreateOrderRequest`.


class Fulfillment::V1::CreateOrderRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      dropoff_location: T.nilable(Common::V1::GeoPoint),
      idempotency_key: T.nilable(Common::V1::IdempotencyKey),
      items: T.nilable(T::Array[Common::V1::OrderItem]),
      merchant_principal_id: T.nilable(String),
      order_number: T.nilable(String),
      pickup_address: T.nilable(Common::V1::Address),
      pickup_location: T.nilable(Common::V1::GeoPoint),
      shipping_address: T.nilable(Common::V1::Address),
      total_amount: T.nilable(Common::V1::Money)
    ).void
  end
  def initialize(dropoff_location: nil, idempotency_key: nil, items: T.unsafe(nil), merchant_principal_id: nil, order_number: nil, pickup_address: nil, pickup_location: nil, shipping_address: nil, total_amount: nil); end

  sig { void }
  def clear_dropoff_location; end

  sig { void }
  def clear_idempotency_key; end

  sig { void }
  def clear_items; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_number; end

  sig { void }
  def clear_pickup_address; end

  sig { void }
  def clear_pickup_location; end

  sig { void }
  def clear_shipping_address; end

  sig { void }
  def clear_total_amount; end

  sig { returns(T.nilable(Common::V1::GeoPoint)) }
  def dropoff_location; end

  sig { params(value: T.nilable(Common::V1::GeoPoint)).void }
  def dropoff_location=(value); end

  sig { returns(Object) }
  def has_dropoff_location?; end

  sig { returns(Object) }
  def has_idempotency_key?; end

  sig { returns(Object) }
  def has_pickup_address?; end

  sig { returns(Object) }
  def has_pickup_location?; end

  sig { returns(Object) }
  def has_shipping_address?; end

  sig { returns(Object) }
  def has_total_amount?; end

  sig { returns(T.nilable(Common::V1::IdempotencyKey)) }
  def idempotency_key; end

  sig { params(value: T.nilable(Common::V1::IdempotencyKey)).void }
  def idempotency_key=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Common::V1::OrderItem]) }
  def items; end

  sig { params(value: Google::Protobuf::RepeatedField[Common::V1::OrderItem]).void }
  def items=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end

  sig { returns(T.nilable(Common::V1::Address)) }
  def pickup_address; end

  sig { params(value: T.nilable(Common::V1::Address)).void }
  def pickup_address=(value); end

  sig { returns(T.nilable(Common::V1::GeoPoint)) }
  def pickup_location; end

  sig { params(value: T.nilable(Common::V1::GeoPoint)).void }
  def pickup_location=(value); end

  sig { returns(T.nilable(Common::V1::Address)) }
  def shipping_address; end

  sig { params(value: T.nilable(Common::V1::Address)).void }
  def shipping_address=(value); end

  sig { returns(T.nilable(Common::V1::Money)) }
  def total_amount; end

  sig { params(value: T.nilable(Common::V1::Money)).void }
  def total_amount=(value); end
end
