# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::GetOrderStatusRequest`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::GetOrderStatusRequest`.


class Fulfillment::V1::GetOrderStatusRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      merchant_principal_id: T.nilable(String),
      order_id: T.nilable(String),
      order_number: T.nilable(String)
    ).void
  end
  def initialize(merchant_principal_id: nil, order_id: nil, order_number: nil); end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_id; end

  sig { void }
  def clear_order_number; end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_id; end

  sig { params(value: String).void }
  def order_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end
end
