# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::GetOrderStatusResponse`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::GetOrderStatusResponse`.


class Fulfillment::V1::GetOrderStatusResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      awb_number: T.nilable(String),
      driver_location: T.nilable(Common::V1::GeoPoint),
      found: T.nilable(T::Boolean),
      order_id: T.nilable(String),
      order_number: T.nilable(String),
      pod_photo_url: T.nilable(String),
      status: T.nilable(T.any(Symbol, Integer)),
      updated_at: T.nilable(Google::Protobuf::Timestamp)
    ).void
  end
  def initialize(awb_number: nil, driver_location: nil, found: nil, order_id: nil, order_number: nil, pod_photo_url: nil, status: nil, updated_at: nil); end

  sig { returns(String) }
  def awb_number; end

  sig { params(value: String).void }
  def awb_number=(value); end

  sig { void }
  def clear_awb_number; end

  sig { void }
  def clear_driver_location; end

  sig { void }
  def clear_found; end

  sig { void }
  def clear_order_id; end

  sig { void }
  def clear_order_number; end

  sig { void }
  def clear_pod_photo_url; end

  sig { void }
  def clear_status; end

  sig { void }
  def clear_updated_at; end

  sig { returns(T.nilable(Common::V1::GeoPoint)) }
  def driver_location; end

  sig { params(value: T.nilable(Common::V1::GeoPoint)).void }
  def driver_location=(value); end

  sig { returns(T::Boolean) }
  def found; end

  sig { params(value: T::Boolean).void }
  def found=(value); end

  sig { returns(Object) }
  def has_driver_location?; end

  sig { returns(Object) }
  def has_updated_at?; end

  sig { returns(String) }
  def order_id; end

  sig { params(value: String).void }
  def order_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end

  sig { returns(String) }
  def pod_photo_url; end

  sig { params(value: String).void }
  def pod_photo_url=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def updated_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def updated_at=(value); end
end
