# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::RecordCourierAwbResponse`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::RecordCourierAwbResponse`.


class Fulfillment::V1::RecordCourierAwbResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      accepted: T.nilable(T::Boolean),
      already_recorded: T.nilable(T::Boolean),
      error: T.nilable(Common::V1::ErrorDetail)
    ).void
  end
  def initialize(accepted: nil, already_recorded: nil, error: nil); end

  sig { returns(T::Boolean) }
  def accepted; end

  sig { params(value: T::Boolean).void }
  def accepted=(value); end

  sig { returns(T::Boolean) }
  def already_recorded; end

  sig { params(value: T::Boolean).void }
  def already_recorded=(value); end

  sig { void }
  def clear_accepted; end

  sig { void }
  def clear_already_recorded; end

  sig { void }
  def clear_error; end

  sig { returns(T.nilable(Common::V1::ErrorDetail)) }
  def error; end

  sig { params(value: T.nilable(Common::V1::ErrorDetail)).void }
  def error=(value); end

  sig { returns(Object) }
  def has_error?; end
end
