# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::RecordCourierAwbRequest`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::RecordCourierAwbRequest`.


class Fulfillment::V1::RecordCourierAwbRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      awb_number: T.nilable(String),
      fulfillment_task_id: T.nilable(String),
      idempotency_key: T.nilable(Common::V1::IdempotencyKey),
      merchant_principal_id: T.nilable(String),
      order_number: T.nilable(String)
    ).void
  end
  def initialize(awb_number: nil, fulfillment_task_id: nil, idempotency_key: nil, merchant_principal_id: nil, order_number: nil); end

  sig { returns(String) }
  def awb_number; end

  sig { params(value: String).void }
  def awb_number=(value); end

  sig { void }
  def clear_awb_number; end

  sig { void }
  def clear_fulfillment_task_id; end

  sig { void }
  def clear_idempotency_key; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_number; end

  sig { returns(String) }
  def fulfillment_task_id; end

  sig { params(value: String).void }
  def fulfillment_task_id=(value); end

  sig { returns(Object) }
  def has_idempotency_key?; end

  sig { returns(T.nilable(Common::V1::IdempotencyKey)) }
  def idempotency_key; end

  sig { params(value: T.nilable(Common::V1::IdempotencyKey)).void }
  def idempotency_key=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end
end
