# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::ReleaseStockRequest`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::ReleaseStockRequest`.


class Fulfillment::V1::ReleaseStockRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      idempotency_key: T.nilable(Common::V1::IdempotencyKey),
      merchant_principal_id: T.nilable(String),
      order_number: T.nilable(String),
      quantity: T.nilable(Integer),
      sku: T.nilable(String)
    ).void
  end
  def initialize(idempotency_key: nil, merchant_principal_id: nil, order_number: nil, quantity: nil, sku: nil); end

  sig { void }
  def clear_idempotency_key; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_number; end

  sig { void }
  def clear_quantity; end

  sig { void }
  def clear_sku; end

  sig { returns(Object) }
  def has_idempotency_key?; end

  sig { returns(T.nilable(Common::V1::IdempotencyKey)) }
  def idempotency_key; end

  sig { params(value: T.nilable(Common::V1::IdempotencyKey)).void }
  def idempotency_key=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end

  sig { returns(Integer) }
  def quantity; end

  sig { params(value: Integer).void }
  def quantity=(value); end

  sig { returns(String) }
  def sku; end

  sig { params(value: String).void }
  def sku=(value); end
end
