# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fulfillment::V1::ReserveStockResponse`.
# Please instead update this file by running `bin/tapioca dsl Fulfillment::V1::ReserveStockResponse`.


class Fulfillment::V1::ReserveStockResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      bin_location: T.nilable(String),
      error: T.nilable(Common::V1::ErrorDetail),
      remaining_available: T.nilable(Integer),
      success: T.nilable(T::Boolean)
    ).void
  end
  def initialize(bin_location: nil, error: nil, remaining_available: nil, success: nil); end

  sig { returns(String) }
  def bin_location; end

  sig { params(value: String).void }
  def bin_location=(value); end

  sig { void }
  def clear_bin_location; end

  sig { void }
  def clear_error; end

  sig { void }
  def clear_remaining_available; end

  sig { void }
  def clear_success; end

  sig { returns(T.nilable(Common::V1::ErrorDetail)) }
  def error; end

  sig { params(value: T.nilable(Common::V1::ErrorDetail)).void }
  def error=(value); end

  sig { returns(Object) }
  def has_error?; end

  sig { returns(Integer) }
  def remaining_available; end

  sig { params(value: Integer).void }
  def remaining_available=(value); end

  sig { returns(T::Boolean) }
  def success; end

  sig { params(value: T::Boolean).void }
  def success=(value); end
end
