# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.


module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def analytics_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_order_returns_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_orders_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def create_ticket_support_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def dispatch_fleet_pulse_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def emergency_halt_orders_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def fleet_radar_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def handover_pdf_manifests_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def health_ready_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def health_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def inventory_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def label_api_v1_order_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def label_view_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def login_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def manifests_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def manual_create_orders_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_source_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def orders_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def print_label_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def queue_api_v1_orders_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_incinerate_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_reroute_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_sources_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailgun_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_postmark_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_relay_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_sendgrid_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def returns_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def scanner_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def start_chat_support_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def status_api_v1_order_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def status_api_v1_return_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def support_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def test_ping_settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def tracking_stream_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_recede_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_refresh_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_resume_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_cutoff_settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_status_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_status_returns_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def verify_scan_url(*args); end
end
