# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MetricsController`.
# Please instead update this file by running `bin/tapioca dsl MetricsController`.


class MetricsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
