# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PruneStockOperationsJob`.
# Please instead update this file by running `bin/tapioca dsl PruneStockOperationsJob`.


class PruneStockOperationsJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: PruneStockOperationsJob).void)
      ).returns(T.any(PruneStockOperationsJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
