# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ReportAbandonedHoldsJob`.
# Please instead update this file by running `bin/tapioca dsl ReportAbandonedHoldsJob`.


class ReportAbandonedHoldsJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: ReportAbandonedHoldsJob).void)
      ).returns(T.any(ReportAbandonedHoldsJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
