# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::FeatureSetDefaults::FeatureSetEditionDefault`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::FeatureSetDefaults::FeatureSetEditionDefault`.


class Google::Protobuf::FeatureSetDefaults::FeatureSetEditionDefault < Google::Protobuf::AbstractMessage
  sig do
    params(
      edition: T.nilable(T.any(Symbol, Integer)),
      fixed_features: T.nilable(Google::Protobuf::FeatureSet),
      overridable_features: T.nilable(Google::Protobuf::FeatureSet)
    ).void
  end
  def initialize(edition: nil, fixed_features: nil, overridable_features: nil); end

  sig { void }
  def clear_edition; end

  sig { void }
  def clear_fixed_features; end

  sig { void }
  def clear_overridable_features; end

  sig { returns(T.any(Symbol, Integer)) }
  def edition; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def edition=(value); end

  sig { returns(T.nilable(Google::Protobuf::FeatureSet)) }
  def fixed_features; end

  sig { params(value: T.nilable(Google::Protobuf::FeatureSet)).void }
  def fixed_features=(value); end

  sig { returns(Object) }
  def has_edition?; end

  sig { returns(Object) }
  def has_fixed_features?; end

  sig { returns(Object) }
  def has_overridable_features?; end

  sig { returns(T.nilable(Google::Protobuf::FeatureSet)) }
  def overridable_features; end

  sig { params(value: T.nilable(Google::Protobuf::FeatureSet)).void }
  def overridable_features=(value); end
end
