# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::FieldOptions::FeatureSupport`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::FieldOptions::FeatureSupport`.


class Google::Protobuf::FieldOptions::FeatureSupport < Google::Protobuf::AbstractMessage
  sig do
    params(
      deprecation_warning: T.nilable(String),
      edition_deprecated: T.nilable(T.any(Symbol, Integer)),
      edition_introduced: T.nilable(T.any(Symbol, Integer)),
      edition_removed: T.nilable(T.any(Symbol, Integer)),
      removal_error: T.nilable(String)
    ).void
  end
  def initialize(deprecation_warning: nil, edition_deprecated: nil, edition_introduced: nil, edition_removed: nil, removal_error: nil); end

  sig { void }
  def clear_deprecation_warning; end

  sig { void }
  def clear_edition_deprecated; end

  sig { void }
  def clear_edition_introduced; end

  sig { void }
  def clear_edition_removed; end

  sig { void }
  def clear_removal_error; end

  sig { returns(String) }
  def deprecation_warning; end

  sig { params(value: String).void }
  def deprecation_warning=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def edition_deprecated; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def edition_deprecated=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def edition_introduced; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def edition_introduced=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def edition_removed; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def edition_removed=(value); end

  sig { returns(Object) }
  def has_deprecation_warning?; end

  sig { returns(Object) }
  def has_edition_deprecated?; end

  sig { returns(Object) }
  def has_edition_introduced?; end

  sig { returns(Object) }
  def has_edition_removed?; end

  sig { returns(Object) }
  def has_removal_error?; end

  sig { returns(String) }
  def removal_error; end

  sig { params(value: String).void }
  def removal_error=(value); end
end
