# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::GetMerchantInfoRequest`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::GetMerchantInfoRequest`.


class Identity::V1::GetMerchantInfoRequest < Google::Protobuf::AbstractMessage
  sig { params(principal_id: T.nilable(String)).void }
  def initialize(principal_id: nil); end

  sig { void }
  def clear_principal_id; end

  sig { returns(String) }
  def principal_id; end

  sig { params(value: String).void }
  def principal_id=(value); end
end
