# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::GetUserProfileResponse`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::GetUserProfileResponse`.


class Identity::V1::GetUserProfileResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      city: T.nilable(String),
      email: T.nilable(String),
      found: T.nilable(T::Boolean),
      full_name: T.nilable(String),
      kind: T.nilable(T.any(Symbol, Integer)),
      phone_number: T.nilable(String),
      postal_code: T.nilable(String),
      principal_id: T.nilable(String),
      street_address: T.nilable(String)
    ).void
  end
  def initialize(city: nil, email: nil, found: nil, full_name: nil, kind: nil, phone_number: nil, postal_code: nil, principal_id: nil, street_address: nil); end

  sig { returns(String) }
  def city; end

  sig { params(value: String).void }
  def city=(value); end

  sig { void }
  def clear_city; end

  sig { void }
  def clear_email; end

  sig { void }
  def clear_found; end

  sig { void }
  def clear_full_name; end

  sig { void }
  def clear_kind; end

  sig { void }
  def clear_phone_number; end

  sig { void }
  def clear_postal_code; end

  sig { void }
  def clear_principal_id; end

  sig { void }
  def clear_street_address; end

  sig { returns(String) }
  def email; end

  sig { params(value: String).void }
  def email=(value); end

  sig { returns(T::Boolean) }
  def found; end

  sig { params(value: T::Boolean).void }
  def found=(value); end

  sig { returns(String) }
  def full_name; end

  sig { params(value: String).void }
  def full_name=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def kind; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def kind=(value); end

  sig { returns(String) }
  def phone_number; end

  sig { params(value: String).void }
  def phone_number=(value); end

  sig { returns(String) }
  def postal_code; end

  sig { params(value: String).void }
  def postal_code=(value); end

  sig { returns(String) }
  def principal_id; end

  sig { params(value: String).void }
  def principal_id=(value); end

  sig { returns(String) }
  def street_address; end

  sig { params(value: String).void }
  def street_address=(value); end
end
