# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::GetMerchantInfoResponse`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::GetMerchantInfoResponse`.


class Identity::V1::GetMerchantInfoResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      business_registration_number: T.nilable(String),
      found: T.nilable(T::Boolean),
      merchant_principal_id: T.nilable(String),
      status: T.nilable(T.any(Symbol, Integer)),
      store_name: T.nilable(String),
      tax_id: T.nilable(String)
    ).void
  end
  def initialize(business_registration_number: nil, found: nil, merchant_principal_id: nil, status: nil, store_name: nil, tax_id: nil); end

  sig { returns(String) }
  def business_registration_number; end

  sig { params(value: String).void }
  def business_registration_number=(value); end

  sig { void }
  def clear_business_registration_number; end

  sig { void }
  def clear_found; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_status; end

  sig { void }
  def clear_store_name; end

  sig { void }
  def clear_tax_id; end

  sig { returns(T::Boolean) }
  def found; end

  sig { params(value: T::Boolean).void }
  def found=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end

  sig { returns(String) }
  def store_name; end

  sig { params(value: String).void }
  def store_name=(value); end

  sig { returns(String) }
  def tax_id; end

  sig { params(value: String).void }
  def tax_id=(value); end
end
