# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::GetMerchantInfoResponse`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::GetMerchantInfoResponse`.


class Identity::V1::GetMerchantInfoResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      business_registration_number: T.nilable(String),
      found: T.nilable(T::Boolean),
      location: T.nilable(Common::V1::GeoPoint),
      may_sell: T.nilable(T::Boolean),
      merchant_principal_id: T.nilable(String),
      pickup_address: T.nilable(Common::V1::Address),
      status: T.nilable(T.any(Symbol, Integer)),
      store_name: T.nilable(String),
      tax_id: T.nilable(String)
    ).void
  end
  def initialize(business_registration_number: nil, found: nil, location: nil, may_sell: nil, merchant_principal_id: nil, pickup_address: nil, status: nil, store_name: nil, tax_id: nil); end

  sig { returns(String) }
  def business_registration_number; end

  sig { params(value: String).void }
  def business_registration_number=(value); end

  sig { void }
  def clear_business_registration_number; end

  sig { void }
  def clear_found; end

  sig { void }
  def clear_location; end

  sig { void }
  def clear_may_sell; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_pickup_address; end

  sig { void }
  def clear_status; end

  sig { void }
  def clear_store_name; end

  sig { void }
  def clear_tax_id; end

  sig { returns(T::Boolean) }
  def found; end

  sig { params(value: T::Boolean).void }
  def found=(value); end

  sig { returns(Object) }
  def has_location?; end

  sig { returns(Object) }
  def has_pickup_address?; end

  sig { returns(T.nilable(Common::V1::GeoPoint)) }
  def location; end

  sig { params(value: T.nilable(Common::V1::GeoPoint)).void }
  def location=(value); end

  sig { returns(T::Boolean) }
  def may_sell; end

  sig { params(value: T::Boolean).void }
  def may_sell=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(T.nilable(Common::V1::Address)) }
  def pickup_address; end

  sig { params(value: T.nilable(Common::V1::Address)).void }
  def pickup_address=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end

  sig { returns(String) }
  def store_name; end

  sig { params(value: String).void }
  def store_name=(value); end

  sig { returns(String) }
  def tax_id; end

  sig { params(value: String).void }
  def tax_id=(value); end
end
