# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::MerchantsChangedSinceResponse`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::MerchantsChangedSinceResponse`.


class Identity::V1::MerchantsChangedSinceResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      has_more: T.nilable(T::Boolean),
      next: T.nilable(Identity::V1::MerchantCursor),
      removed_principal_ids: T.nilable(T::Array[String]),
      upserted: T.nilable(T::Array[Identity::V1::MerchantRecord])
    ).void
  end
  def initialize(has_more: nil, next: nil, removed_principal_ids: T.unsafe(nil), upserted: T.unsafe(nil)); end

  sig { void }
  def clear_has_more; end

  sig { void }
  def clear_next; end

  sig { void }
  def clear_removed_principal_ids; end

  sig { void }
  def clear_upserted; end

  sig { returns(T::Boolean) }
  def has_more; end

  sig { params(value: T::Boolean).void }
  def has_more=(value); end

  sig { returns(Object) }
  def has_next?; end

  sig { returns(T.nilable(Identity::V1::MerchantCursor)) }
  def next; end

  sig { params(value: T.nilable(Identity::V1::MerchantCursor)).void }
  def next=(value); end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def removed_principal_ids; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def removed_principal_ids=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Identity::V1::MerchantRecord]) }
  def upserted; end

  sig { params(value: Google::Protobuf::RepeatedField[Identity::V1::MerchantRecord]).void }
  def upserted=(value); end
end
