# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::MerchantCursor`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::MerchantCursor`.


class Identity::V1::MerchantCursor < Google::Protobuf::AbstractMessage
  sig { params(last_principal_id: T.nilable(String), updated_through: T.nilable(Google::Protobuf::Timestamp)).void }
  def initialize(last_principal_id: nil, updated_through: nil); end

  sig { void }
  def clear_last_principal_id; end

  sig { void }
  def clear_updated_through; end

  sig { returns(Object) }
  def has_updated_through?; end

  sig { returns(String) }
  def last_principal_id; end

  sig { params(value: String).void }
  def last_principal_id=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def updated_through; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def updated_through=(value); end
end
