# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::MerchantRecord`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::MerchantRecord`.


class Identity::V1::MerchantRecord < Google::Protobuf::AbstractMessage
  sig do
    params(
      may_sell: T.nilable(T::Boolean),
      principal_id: T.nilable(String),
      status: T.nilable(T.any(Symbol, Integer)),
      store_name: T.nilable(String),
      updated_at: T.nilable(Google::Protobuf::Timestamp)
    ).void
  end
  def initialize(may_sell: nil, principal_id: nil, status: nil, store_name: nil, updated_at: nil); end

  sig { void }
  def clear_may_sell; end

  sig { void }
  def clear_principal_id; end

  sig { void }
  def clear_status; end

  sig { void }
  def clear_store_name; end

  sig { void }
  def clear_updated_at; end

  sig { returns(Object) }
  def has_updated_at?; end

  sig { returns(T::Boolean) }
  def may_sell; end

  sig { params(value: T::Boolean).void }
  def may_sell=(value); end

  sig { returns(String) }
  def principal_id; end

  sig { params(value: String).void }
  def principal_id=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end

  sig { returns(String) }
  def store_name; end

  sig { params(value: String).void }
  def store_name=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def updated_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def updated_at=(value); end
end
