# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::MerchantStatus`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::MerchantStatus`.


module Identity::V1::MerchantStatus
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Identity::V1::MerchantStatus::MERCHANT_STATUS_CLOSED = 4
Identity::V1::MerchantStatus::MERCHANT_STATUS_PENDING = 1
Identity::V1::MerchantStatus::MERCHANT_STATUS_SUSPENDED = 3
Identity::V1::MerchantStatus::MERCHANT_STATUS_UNSPECIFIED = 0
Identity::V1::MerchantStatus::MERCHANT_STATUS_VERIFIED = 2
