# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::MerchantsChangedSinceRequest`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::MerchantsChangedSinceRequest`.


class Identity::V1::MerchantsChangedSinceRequest < Google::Protobuf::AbstractMessage
  sig { params(cursor: T.nilable(Identity::V1::MerchantCursor), limit: T.nilable(Integer)).void }
  def initialize(cursor: nil, limit: nil); end

  sig { void }
  def clear_cursor; end

  sig { void }
  def clear_limit; end

  sig { returns(T.nilable(Identity::V1::MerchantCursor)) }
  def cursor; end

  sig { params(value: T.nilable(Identity::V1::MerchantCursor)).void }
  def cursor=(value); end

  sig { returns(Object) }
  def has_cursor?; end

  sig { returns(Integer) }
  def limit; end

  sig { params(value: Integer).void }
  def limit=(value); end
end
