# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::PrincipalKind`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::PrincipalKind`.


module Identity::V1::PrincipalKind
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Identity::V1::PrincipalKind::PRINCIPAL_KIND_CUSTOMER = 1
Identity::V1::PrincipalKind::PRINCIPAL_KIND_DRIVER = 3
Identity::V1::PrincipalKind::PRINCIPAL_KIND_MERCHANT = 2
Identity::V1::PrincipalKind::PRINCIPAL_KIND_SERVICE = 5
Identity::V1::PrincipalKind::PRINCIPAL_KIND_STAFF = 4
Identity::V1::PrincipalKind::PRINCIPAL_KIND_UNSPECIFIED = 0
