# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::ResolvePrincipalRequest`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::ResolvePrincipalRequest`.


class Identity::V1::ResolvePrincipalRequest < Google::Protobuf::AbstractMessage
  sig { params(service_local_id: T.nilable(Identity::V1::ServiceLocalId)).void }
  def initialize(service_local_id: nil); end

  sig { void }
  def clear_service_local_id; end

  sig { returns(Object) }
  def has_service_local_id?; end

  sig { returns(T.nilable(Identity::V1::ServiceLocalId)) }
  def service_local_id; end

  sig { params(value: T.nilable(Identity::V1::ServiceLocalId)).void }
  def service_local_id=(value); end
end
