# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::ResolvePrincipalResponse`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::ResolvePrincipalResponse`.


class Identity::V1::ResolvePrincipalResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      display_name: T.nilable(String),
      found: T.nilable(T::Boolean),
      kind: T.nilable(T.any(Symbol, Integer)),
      principal_id: T.nilable(String)
    ).void
  end
  def initialize(display_name: nil, found: nil, kind: nil, principal_id: nil); end

  sig { void }
  def clear_display_name; end

  sig { void }
  def clear_found; end

  sig { void }
  def clear_kind; end

  sig { void }
  def clear_principal_id; end

  sig { returns(String) }
  def display_name; end

  sig { params(value: String).void }
  def display_name=(value); end

  sig { returns(T::Boolean) }
  def found; end

  sig { params(value: T::Boolean).void }
  def found=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def kind; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def kind=(value); end

  sig { returns(String) }
  def principal_id; end

  sig { params(value: String).void }
  def principal_id=(value); end
end
