# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::ServiceLocalId`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::ServiceLocalId`.


class Identity::V1::ServiceLocalId < Google::Protobuf::AbstractMessage
  sig { params(local_id: T.nilable(String), service: T.nilable(String)).void }
  def initialize(local_id: nil, service: nil); end

  sig { void }
  def clear_local_id; end

  sig { void }
  def clear_service; end

  sig { returns(String) }
  def local_id; end

  sig { params(value: String).void }
  def local_id=(value); end

  sig { returns(String) }
  def service; end

  sig { params(value: String).void }
  def service=(value); end
end
