# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::ValidateTokenResponse`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::ValidateTokenResponse`.


class Identity::V1::ValidateTokenResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      kind: T.nilable(T.any(Symbol, Integer)),
      principal_id: T.nilable(String),
      reason: T.nilable(String),
      valid: T.nilable(T::Boolean)
    ).void
  end
  def initialize(kind: nil, principal_id: nil, reason: nil, valid: nil); end

  sig { void }
  def clear_kind; end

  sig { void }
  def clear_principal_id; end

  sig { void }
  def clear_reason; end

  sig { void }
  def clear_valid; end

  sig { returns(T.any(Symbol, Integer)) }
  def kind; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def kind=(value); end

  sig { returns(String) }
  def principal_id; end

  sig { params(value: String).void }
  def principal_id=(value); end

  sig { returns(String) }
  def reason; end

  sig { params(value: String).void }
  def reason=(value); end

  sig { returns(T::Boolean) }
  def valid; end

  sig { params(value: T::Boolean).void }
  def valid=(value); end
end
