# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Identity::V1::ValidateTokenRequest`.
# Please instead update this file by running `bin/tapioca dsl Identity::V1::ValidateTokenRequest`.


class Identity::V1::ValidateTokenRequest < Google::Protobuf::AbstractMessage
  sig { params(access_token: T.nilable(String)).void }
  def initialize(access_token: nil); end

  sig { returns(String) }
  def access_token; end

  sig { params(value: String).void }
  def access_token=(value); end

  sig { void }
  def clear_access_token; end
end
