# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grpc::Reflection::V1::ExtensionRequest`.
# Please instead update this file by running `bin/tapioca dsl Grpc::Reflection::V1::ExtensionRequest`.


class Grpc::Reflection::V1::ExtensionRequest < Google::Protobuf::AbstractMessage
  sig { params(containing_type: T.nilable(String), extension_number: T.nilable(Integer)).void }
  def initialize(containing_type: nil, extension_number: nil); end

  sig { void }
  def clear_containing_type; end

  sig { void }
  def clear_extension_number; end

  sig { returns(String) }
  def containing_type; end

  sig { params(value: String).void }
  def containing_type=(value); end

  sig { returns(Integer) }
  def extension_number; end

  sig { params(value: Integer).void }
  def extension_number=(value); end
end
