# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grpc::Reflection::V1::ExtensionNumberResponse`.
# Please instead update this file by running `bin/tapioca dsl Grpc::Reflection::V1::ExtensionNumberResponse`.


class Grpc::Reflection::V1::ExtensionNumberResponse < Google::Protobuf::AbstractMessage
  sig { params(base_type_name: T.nilable(String), extension_number: T.nilable(T::Array[Integer])).void }
  def initialize(base_type_name: nil, extension_number: T.unsafe(nil)); end

  sig { returns(String) }
  def base_type_name; end

  sig { params(value: String).void }
  def base_type_name=(value); end

  sig { void }
  def clear_base_type_name; end

  sig { void }
  def clear_extension_number; end

  sig { returns(Google::Protobuf::RepeatedField[Integer]) }
  def extension_number; end

  sig { params(value: Google::Protobuf::RepeatedField[Integer]).void }
  def extension_number=(value); end
end
