# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grpc::Reflection::V1::FileDescriptorResponse`.
# Please instead update this file by running `bin/tapioca dsl Grpc::Reflection::V1::FileDescriptorResponse`.


class Grpc::Reflection::V1::FileDescriptorResponse < Google::Protobuf::AbstractMessage
  sig { params(file_descriptor_proto: T.nilable(T::Array[String])).void }
  def initialize(file_descriptor_proto: T.unsafe(nil)); end

  sig { void }
  def clear_file_descriptor_proto; end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def file_descriptor_proto; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def file_descriptor_proto=(value); end
end
