# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grpc::Reflection::V1::ServiceResponse`.
# Please instead update this file by running `bin/tapioca dsl Grpc::Reflection::V1::ServiceResponse`.


class Grpc::Reflection::V1::ServiceResponse < Google::Protobuf::AbstractMessage
  sig { params(name: T.nilable(String)).void }
  def initialize(name: nil); end

  sig { void }
  def clear_name; end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end
end
