# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fleet::V1::DispatchCourierResponse`.
# Please instead update this file by running `bin/tapioca dsl Fleet::V1::DispatchCourierResponse`.


class Fleet::V1::DispatchCourierResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      assigned_driver_name: T.nilable(String),
      assigned_driver_phone: T.nilable(String),
      assigned_driver_principal_id: T.nilable(String),
      dispatch_ref: T.nilable(String),
      error: T.nilable(Common::V1::ErrorDetail),
      eta_minutes: T.nilable(Integer),
      success: T.nilable(T::Boolean),
      vehicle: T.nilable(String)
    ).void
  end
  def initialize(assigned_driver_name: nil, assigned_driver_phone: nil, assigned_driver_principal_id: nil, dispatch_ref: nil, error: nil, eta_minutes: nil, success: nil, vehicle: nil); end

  sig { returns(String) }
  def assigned_driver_name; end

  sig { params(value: String).void }
  def assigned_driver_name=(value); end

  sig { returns(String) }
  def assigned_driver_phone; end

  sig { params(value: String).void }
  def assigned_driver_phone=(value); end

  sig { returns(String) }
  def assigned_driver_principal_id; end

  sig { params(value: String).void }
  def assigned_driver_principal_id=(value); end

  sig { void }
  def clear_assigned_driver_name; end

  sig { void }
  def clear_assigned_driver_phone; end

  sig { void }
  def clear_assigned_driver_principal_id; end

  sig { void }
  def clear_dispatch_ref; end

  sig { void }
  def clear_error; end

  sig { void }
  def clear_eta_minutes; end

  sig { void }
  def clear_success; end

  sig { void }
  def clear_vehicle; end

  sig { returns(String) }
  def dispatch_ref; end

  sig { params(value: String).void }
  def dispatch_ref=(value); end

  sig { returns(T.nilable(Common::V1::ErrorDetail)) }
  def error; end

  sig { params(value: T.nilable(Common::V1::ErrorDetail)).void }
  def error=(value); end

  sig { returns(Integer) }
  def eta_minutes; end

  sig { params(value: Integer).void }
  def eta_minutes=(value); end

  sig { returns(Object) }
  def has_error?; end

  sig { returns(T::Boolean) }
  def success; end

  sig { params(value: T::Boolean).void }
  def success=(value); end

  sig { returns(String) }
  def vehicle; end

  sig { params(value: String).void }
  def vehicle=(value); end
end
