# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fleet::V1::DispatchCourierRequest`.
# Please instead update this file by running `bin/tapioca dsl Fleet::V1::DispatchCourierRequest`.


class Fleet::V1::DispatchCourierRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      delivery_address: T.nilable(Common::V1::Address),
      idempotency_key: T.nilable(Common::V1::IdempotencyKey),
      merchant_principal_id: T.nilable(String),
      order_id: T.nilable(String),
      order_number: T.nilable(String),
      pickup_address: T.nilable(Common::V1::Address)
    ).void
  end
  def initialize(delivery_address: nil, idempotency_key: nil, merchant_principal_id: nil, order_id: nil, order_number: nil, pickup_address: nil); end

  sig { void }
  def clear_delivery_address; end

  sig { void }
  def clear_idempotency_key; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_id; end

  sig { void }
  def clear_order_number; end

  sig { void }
  def clear_pickup_address; end

  sig { returns(T.nilable(Common::V1::Address)) }
  def delivery_address; end

  sig { params(value: T.nilable(Common::V1::Address)).void }
  def delivery_address=(value); end

  sig { returns(Object) }
  def has_delivery_address?; end

  sig { returns(Object) }
  def has_idempotency_key?; end

  sig { returns(Object) }
  def has_pickup_address?; end

  sig { returns(T.nilable(Common::V1::IdempotencyKey)) }
  def idempotency_key; end

  sig { params(value: T.nilable(Common::V1::IdempotencyKey)).void }
  def idempotency_key=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_id; end

  sig { params(value: String).void }
  def order_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end

  sig { returns(T.nilable(Common::V1::Address)) }
  def pickup_address; end

  sig { params(value: T.nilable(Common::V1::Address)).void }
  def pickup_address=(value); end
end
