# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fleet::V1::DriverLocationAck`.
# Please instead update this file by running `bin/tapioca dsl Fleet::V1::DriverLocationAck`.


class Fleet::V1::DriverLocationAck < Google::Protobuf::AbstractMessage
  sig do
    params(
      driver_principal_id: T.nilable(String),
      received: T.nilable(T::Boolean),
      server_time: T.nilable(Google::Protobuf::Timestamp)
    ).void
  end
  def initialize(driver_principal_id: nil, received: nil, server_time: nil); end

  sig { void }
  def clear_driver_principal_id; end

  sig { void }
  def clear_received; end

  sig { void }
  def clear_server_time; end

  sig { returns(String) }
  def driver_principal_id; end

  sig { params(value: String).void }
  def driver_principal_id=(value); end

  sig { returns(Object) }
  def has_server_time?; end

  sig { returns(T::Boolean) }
  def received; end

  sig { params(value: T::Boolean).void }
  def received=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def server_time; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def server_time=(value); end
end
