# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fleet::V1::DriverLocationPing`.
# Please instead update this file by running `bin/tapioca dsl Fleet::V1::DriverLocationPing`.


class Fleet::V1::DriverLocationPing < Google::Protobuf::AbstractMessage
  sig do
    params(
      driver_principal_id: T.nilable(String),
      location: T.nilable(Common::V1::GeoPoint),
      observed_at: T.nilable(Google::Protobuf::Timestamp),
      order_number: T.nilable(String),
      speed_kmh: T.nilable(Float),
      status: T.nilable(T.any(Symbol, Integer))
    ).void
  end
  def initialize(driver_principal_id: nil, location: nil, observed_at: nil, order_number: nil, speed_kmh: nil, status: nil); end

  sig { void }
  def clear_driver_principal_id; end

  sig { void }
  def clear_location; end

  sig { void }
  def clear_observed_at; end

  sig { void }
  def clear_order_number; end

  sig { void }
  def clear_speed_kmh; end

  sig { void }
  def clear_status; end

  sig { returns(String) }
  def driver_principal_id; end

  sig { params(value: String).void }
  def driver_principal_id=(value); end

  sig { returns(Object) }
  def has_location?; end

  sig { returns(Object) }
  def has_observed_at?; end

  sig { returns(T.nilable(Common::V1::GeoPoint)) }
  def location; end

  sig { params(value: T.nilable(Common::V1::GeoPoint)).void }
  def location=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def observed_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def observed_at=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end

  sig { returns(Float) }
  def speed_kmh; end

  sig { params(value: Float).void }
  def speed_kmh=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end
end
