# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::FeatureSet::EnforceNamingStyle`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::FeatureSet::EnforceNamingStyle`.


module Google::Protobuf::FeatureSet::EnforceNamingStyle
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Google::Protobuf::FeatureSet::EnforceNamingStyle::ENFORCE_NAMING_STYLE_UNKNOWN = 0
Google::Protobuf::FeatureSet::EnforceNamingStyle::STYLE2024 = 1
Google::Protobuf::FeatureSet::EnforceNamingStyle::STYLE2026 = 3
Google::Protobuf::FeatureSet::EnforceNamingStyle::STYLE_LEGACY = 2
