# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::FeatureSet::ProtoLimitsFeature`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::FeatureSet::ProtoLimitsFeature`.


class Google::Protobuf::FeatureSet::ProtoLimitsFeature < Google::Protobuf::AbstractMessage
  sig { void }
  def initialize; end
end
