# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::FeatureSet::VisibilityFeature`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::FeatureSet::VisibilityFeature`.


class Google::Protobuf::FeatureSet::VisibilityFeature < Google::Protobuf::AbstractMessage
  sig { void }
  def initialize; end
end
