# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::FulfillmentPackedRequest`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::FulfillmentPackedRequest`.


class Order::V1::FulfillmentPackedRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      fulfillment_task_id: T.nilable(String),
      merchant_principal_id: T.nilable(String),
      order_number: T.nilable(String)
    ).void
  end
  def initialize(fulfillment_task_id: nil, merchant_principal_id: nil, order_number: nil); end

  sig { void }
  def clear_fulfillment_task_id; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_number; end

  sig { returns(String) }
  def fulfillment_task_id; end

  sig { params(value: String).void }
  def fulfillment_task_id=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end
end
