# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::FulfillmentPackedResponse`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::FulfillmentPackedResponse`.


class Order::V1::FulfillmentPackedResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      already_packed: T.nilable(T::Boolean),
      dispatch_ref: T.nilable(String),
      error: T.nilable(Common::V1::ErrorDetail),
      success: T.nilable(T::Boolean)
    ).void
  end
  def initialize(already_packed: nil, dispatch_ref: nil, error: nil, success: nil); end

  sig { returns(T::Boolean) }
  def already_packed; end

  sig { params(value: T::Boolean).void }
  def already_packed=(value); end

  sig { void }
  def clear_already_packed; end

  sig { void }
  def clear_dispatch_ref; end

  sig { void }
  def clear_error; end

  sig { void }
  def clear_success; end

  sig { returns(String) }
  def dispatch_ref; end

  sig { params(value: String).void }
  def dispatch_ref=(value); end

  sig { returns(T.nilable(Common::V1::ErrorDetail)) }
  def error; end

  sig { params(value: T.nilable(Common::V1::ErrorDetail)).void }
  def error=(value); end

  sig { returns(Object) }
  def has_error?; end

  sig { returns(T::Boolean) }
  def success; end

  sig { params(value: T::Boolean).void }
  def success=(value); end
end
