# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::GetOrderDetailsResponse`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::GetOrderDetailsResponse`.


class Order::V1::GetOrderDetailsResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      customer_principal_id: T.nilable(String),
      discount_amount: T.nilable(Common::V1::Money),
      final_total: T.nilable(Common::V1::Money),
      found: T.nilable(T::Boolean),
      lines: T.nilable(T::Array[Order::V1::OrderLine]),
      order_id: T.nilable(String),
      order_number: T.nilable(String),
      shipping_address: T.nilable(Common::V1::Address),
      shipping_fee: T.nilable(Common::V1::Money),
      status: T.nilable(T.any(Symbol, Integer)),
      subtotal: T.nilable(Common::V1::Money)
    ).void
  end
  def initialize(customer_principal_id: nil, discount_amount: nil, final_total: nil, found: nil, lines: T.unsafe(nil), order_id: nil, order_number: nil, shipping_address: nil, shipping_fee: nil, status: nil, subtotal: nil); end

  sig { void }
  def clear_customer_principal_id; end

  sig { void }
  def clear_discount_amount; end

  sig { void }
  def clear_final_total; end

  sig { void }
  def clear_found; end

  sig { void }
  def clear_lines; end

  sig { void }
  def clear_order_id; end

  sig { void }
  def clear_order_number; end

  sig { void }
  def clear_shipping_address; end

  sig { void }
  def clear_shipping_fee; end

  sig { void }
  def clear_status; end

  sig { void }
  def clear_subtotal; end

  sig { returns(String) }
  def customer_principal_id; end

  sig { params(value: String).void }
  def customer_principal_id=(value); end

  sig { returns(T.nilable(Common::V1::Money)) }
  def discount_amount; end

  sig { params(value: T.nilable(Common::V1::Money)).void }
  def discount_amount=(value); end

  sig { returns(T.nilable(Common::V1::Money)) }
  def final_total; end

  sig { params(value: T.nilable(Common::V1::Money)).void }
  def final_total=(value); end

  sig { returns(T::Boolean) }
  def found; end

  sig { params(value: T::Boolean).void }
  def found=(value); end

  sig { returns(Object) }
  def has_discount_amount?; end

  sig { returns(Object) }
  def has_final_total?; end

  sig { returns(Object) }
  def has_shipping_address?; end

  sig { returns(Object) }
  def has_shipping_fee?; end

  sig { returns(Object) }
  def has_subtotal?; end

  sig { returns(Google::Protobuf::RepeatedField[Order::V1::OrderLine]) }
  def lines; end

  sig { params(value: Google::Protobuf::RepeatedField[Order::V1::OrderLine]).void }
  def lines=(value); end

  sig { returns(String) }
  def order_id; end

  sig { params(value: String).void }
  def order_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end

  sig { returns(T.nilable(Common::V1::Address)) }
  def shipping_address; end

  sig { params(value: T.nilable(Common::V1::Address)).void }
  def shipping_address=(value); end

  sig { returns(T.nilable(Common::V1::Money)) }
  def shipping_fee; end

  sig { params(value: T.nilable(Common::V1::Money)).void }
  def shipping_fee=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end

  sig { returns(T.nilable(Common::V1::Money)) }
  def subtotal; end

  sig { params(value: T.nilable(Common::V1::Money)).void }
  def subtotal=(value); end
end
