# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::GetOrderDetailsRequest`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::GetOrderDetailsRequest`.


class Order::V1::GetOrderDetailsRequest < Google::Protobuf::AbstractMessage
  sig { params(order_id: T.nilable(String)).void }
  def initialize(order_id: nil); end

  sig { void }
  def clear_order_id; end

  sig { returns(String) }
  def order_id; end

  sig { params(value: String).void }
  def order_id=(value); end
end
