# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::ListOrdersForPrincipalResponse`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::ListOrdersForPrincipalResponse`.


class Order::V1::ListOrdersForPrincipalResponse < Google::Protobuf::AbstractMessage
  sig { params(orders: T.nilable(T::Array[Order::V1::GetOrderDetailsResponse]), total_count: T.nilable(Integer)).void }
  def initialize(orders: T.unsafe(nil), total_count: nil); end

  sig { void }
  def clear_orders; end

  sig { void }
  def clear_total_count; end

  sig { returns(Google::Protobuf::RepeatedField[Order::V1::GetOrderDetailsResponse]) }
  def orders; end

  sig { params(value: Google::Protobuf::RepeatedField[Order::V1::GetOrderDetailsResponse]).void }
  def orders=(value); end

  sig { returns(Integer) }
  def total_count; end

  sig { params(value: Integer).void }
  def total_count=(value); end
end
