# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::ListOrdersForPrincipalRequest`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::ListOrdersForPrincipalRequest`.


class Order::V1::ListOrdersForPrincipalRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      page: T.nilable(Integer),
      page_size: T.nilable(Integer),
      principal_id: T.nilable(String),
      status: T.nilable(T.any(Symbol, Integer))
    ).void
  end
  def initialize(page: nil, page_size: nil, principal_id: nil, status: nil); end

  sig { void }
  def clear_page; end

  sig { void }
  def clear_page_size; end

  sig { void }
  def clear_principal_id; end

  sig { void }
  def clear_status; end

  sig { returns(Integer) }
  def page; end

  sig { params(value: Integer).void }
  def page=(value); end

  sig { returns(Integer) }
  def page_size; end

  sig { params(value: Integer).void }
  def page_size=(value); end

  sig { returns(String) }
  def principal_id; end

  sig { params(value: String).void }
  def principal_id=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end
end
