# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::OpenReturnResponse`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::OpenReturnResponse`.


class Order::V1::OpenReturnResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      already_open: T.nilable(T::Boolean),
      error: T.nilable(Common::V1::ErrorDetail),
      return_number: T.nilable(String),
      status: T.nilable(T.any(Symbol, Integer)),
      success: T.nilable(T::Boolean)
    ).void
  end
  def initialize(already_open: nil, error: nil, return_number: nil, status: nil, success: nil); end

  sig { returns(T::Boolean) }
  def already_open; end

  sig { params(value: T::Boolean).void }
  def already_open=(value); end

  sig { void }
  def clear_already_open; end

  sig { void }
  def clear_error; end

  sig { void }
  def clear_return_number; end

  sig { void }
  def clear_status; end

  sig { void }
  def clear_success; end

  sig { returns(T.nilable(Common::V1::ErrorDetail)) }
  def error; end

  sig { params(value: T.nilable(Common::V1::ErrorDetail)).void }
  def error=(value); end

  sig { returns(Object) }
  def has_error?; end

  sig { returns(String) }
  def return_number; end

  sig { params(value: String).void }
  def return_number=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end

  sig { returns(T::Boolean) }
  def success; end

  sig { params(value: T::Boolean).void }
  def success=(value); end
end
