# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::OrdersChangedSinceRequest`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::OrdersChangedSinceRequest`.


class Order::V1::OrdersChangedSinceRequest < Google::Protobuf::AbstractMessage
  sig { params(cursor: T.nilable(Order::V1::OrderCursor), limit: T.nilable(Integer)).void }
  def initialize(cursor: nil, limit: nil); end

  sig { void }
  def clear_cursor; end

  sig { void }
  def clear_limit; end

  sig { returns(T.nilable(Order::V1::OrderCursor)) }
  def cursor; end

  sig { params(value: T.nilable(Order::V1::OrderCursor)).void }
  def cursor=(value); end

  sig { returns(Object) }
  def has_cursor?; end

  sig { returns(Integer) }
  def limit; end

  sig { params(value: Integer).void }
  def limit=(value); end
end
