# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::OrderDeliveredRequest`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::OrderDeliveredRequest`.


class Order::V1::OrderDeliveredRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      delivered_at: T.nilable(String),
      driver_principal_id: T.nilable(String),
      order_number: T.nilable(String)
    ).void
  end
  def initialize(delivered_at: nil, driver_principal_id: nil, order_number: nil); end

  sig { void }
  def clear_delivered_at; end

  sig { void }
  def clear_driver_principal_id; end

  sig { void }
  def clear_order_number; end

  sig { returns(String) }
  def delivered_at; end

  sig { params(value: String).void }
  def delivered_at=(value); end

  sig { returns(String) }
  def driver_principal_id; end

  sig { params(value: String).void }
  def driver_principal_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end
end
