# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::OrderDeliveredResponse`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::OrderDeliveredResponse`.


class Order::V1::OrderDeliveredResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      accepted: T.nilable(T::Boolean),
      already_delivered: T.nilable(T::Boolean),
      error: T.nilable(Common::V1::ErrorDetail)
    ).void
  end
  def initialize(accepted: nil, already_delivered: nil, error: nil); end

  sig { returns(T::Boolean) }
  def accepted; end

  sig { params(value: T::Boolean).void }
  def accepted=(value); end

  sig { returns(T::Boolean) }
  def already_delivered; end

  sig { params(value: T::Boolean).void }
  def already_delivered=(value); end

  sig { void }
  def clear_accepted; end

  sig { void }
  def clear_already_delivered; end

  sig { void }
  def clear_error; end

  sig { returns(T.nilable(Common::V1::ErrorDetail)) }
  def error; end

  sig { params(value: T.nilable(Common::V1::ErrorDetail)).void }
  def error=(value); end

  sig { returns(Object) }
  def has_error?; end
end
