# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::OrdersChangedSinceResponse`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::OrdersChangedSinceResponse`.


class Order::V1::OrdersChangedSinceResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      has_more: T.nilable(T::Boolean),
      next: T.nilable(Order::V1::OrderCursor),
      upserted: T.nilable(T::Array[Order::V1::OrderRecord])
    ).void
  end
  def initialize(has_more: nil, next: nil, upserted: T.unsafe(nil)); end

  sig { void }
  def clear_has_more; end

  sig { void }
  def clear_next; end

  sig { void }
  def clear_upserted; end

  sig { returns(T::Boolean) }
  def has_more; end

  sig { params(value: T::Boolean).void }
  def has_more=(value); end

  sig { returns(Object) }
  def has_next?; end

  sig { returns(T.nilable(Order::V1::OrderCursor)) }
  def next; end

  sig { params(value: T.nilable(Order::V1::OrderCursor)).void }
  def next=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Order::V1::OrderRecord]) }
  def upserted; end

  sig { params(value: Google::Protobuf::RepeatedField[Order::V1::OrderRecord]).void }
  def upserted=(value); end
end
