# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::OrderRecord`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::OrderRecord`.


class Order::V1::OrderRecord < Google::Protobuf::AbstractMessage
  sig do
    params(
      buyer_principal_id: T.nilable(String),
      line_titles: T.nilable(T::Array[String]),
      merchant_principal_id: T.nilable(String),
      order_number: T.nilable(String),
      placed_at: T.nilable(Google::Protobuf::Timestamp),
      status: T.nilable(T.any(Symbol, Integer)),
      updated_at: T.nilable(Google::Protobuf::Timestamp)
    ).void
  end
  def initialize(buyer_principal_id: nil, line_titles: T.unsafe(nil), merchant_principal_id: nil, order_number: nil, placed_at: nil, status: nil, updated_at: nil); end

  sig { returns(String) }
  def buyer_principal_id; end

  sig { params(value: String).void }
  def buyer_principal_id=(value); end

  sig { void }
  def clear_buyer_principal_id; end

  sig { void }
  def clear_line_titles; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_order_number; end

  sig { void }
  def clear_placed_at; end

  sig { void }
  def clear_status; end

  sig { void }
  def clear_updated_at; end

  sig { returns(Object) }
  def has_placed_at?; end

  sig { returns(Object) }
  def has_updated_at?; end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def line_titles; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def line_titles=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def order_number; end

  sig { params(value: String).void }
  def order_number=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def placed_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def placed_at=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def updated_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def updated_at=(value); end
end
