# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::OrderLine`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::OrderLine`.


class Order::V1::OrderLine < Google::Protobuf::AbstractMessage
  sig do
    params(
      line_subtotal: T.nilable(Common::V1::Money),
      product_id: T.nilable(String),
      product_title: T.nilable(String),
      quantity: T.nilable(Integer),
      unit_price: T.nilable(Common::V1::Money)
    ).void
  end
  def initialize(line_subtotal: nil, product_id: nil, product_title: nil, quantity: nil, unit_price: nil); end

  sig { void }
  def clear_line_subtotal; end

  sig { void }
  def clear_product_id; end

  sig { void }
  def clear_product_title; end

  sig { void }
  def clear_quantity; end

  sig { void }
  def clear_unit_price; end

  sig { returns(Object) }
  def has_line_subtotal?; end

  sig { returns(Object) }
  def has_unit_price?; end

  sig { returns(T.nilable(Common::V1::Money)) }
  def line_subtotal; end

  sig { params(value: T.nilable(Common::V1::Money)).void }
  def line_subtotal=(value); end

  sig { returns(String) }
  def product_id; end

  sig { params(value: String).void }
  def product_id=(value); end

  sig { returns(String) }
  def product_title; end

  sig { params(value: String).void }
  def product_title=(value); end

  sig { returns(Integer) }
  def quantity; end

  sig { params(value: Integer).void }
  def quantity=(value); end

  sig { returns(T.nilable(Common::V1::Money)) }
  def unit_price; end

  sig { params(value: T.nilable(Common::V1::Money)).void }
  def unit_price=(value); end
end
