# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::OrderCursor`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::OrderCursor`.


class Order::V1::OrderCursor < Google::Protobuf::AbstractMessage
  sig { params(last_order_number: T.nilable(String), updated_through: T.nilable(Google::Protobuf::Timestamp)).void }
  def initialize(last_order_number: nil, updated_through: nil); end

  sig { void }
  def clear_last_order_number; end

  sig { void }
  def clear_updated_through; end

  sig { returns(Object) }
  def has_updated_through?; end

  sig { returns(String) }
  def last_order_number; end

  sig { params(value: String).void }
  def last_order_number=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def updated_through; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def updated_through=(value); end
end
