# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::ReturnGoodsReceivedRequest`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::ReturnGoodsReceivedRequest`.


class Order::V1::ReturnGoodsReceivedRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      bin_code: T.nilable(String),
      idempotency_key: T.nilable(Common::V1::IdempotencyKey),
      lines: T.nilable(T::Array[Order::V1::ReturnedLine]),
      merchant_principal_id: T.nilable(String),
      received_at: T.nilable(String),
      return_number: T.nilable(String)
    ).void
  end
  def initialize(bin_code: nil, idempotency_key: nil, lines: T.unsafe(nil), merchant_principal_id: nil, received_at: nil, return_number: nil); end

  sig { returns(String) }
  def bin_code; end

  sig { params(value: String).void }
  def bin_code=(value); end

  sig { void }
  def clear_bin_code; end

  sig { void }
  def clear_idempotency_key; end

  sig { void }
  def clear_lines; end

  sig { void }
  def clear_merchant_principal_id; end

  sig { void }
  def clear_received_at; end

  sig { void }
  def clear_return_number; end

  sig { returns(Object) }
  def has_idempotency_key?; end

  sig { returns(T.nilable(Common::V1::IdempotencyKey)) }
  def idempotency_key; end

  sig { params(value: T.nilable(Common::V1::IdempotencyKey)).void }
  def idempotency_key=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Order::V1::ReturnedLine]) }
  def lines; end

  sig { params(value: Google::Protobuf::RepeatedField[Order::V1::ReturnedLine]).void }
  def lines=(value); end

  sig { returns(String) }
  def merchant_principal_id; end

  sig { params(value: String).void }
  def merchant_principal_id=(value); end

  sig { returns(String) }
  def received_at; end

  sig { params(value: String).void }
  def received_at=(value); end

  sig { returns(String) }
  def return_number; end

  sig { params(value: String).void }
  def return_number=(value); end
end
