# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::ReturnedLine`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::ReturnedLine`.


class Order::V1::ReturnedLine < Google::Protobuf::AbstractMessage
  sig { params(quantity: T.nilable(Integer), sku: T.nilable(String)).void }
  def initialize(quantity: nil, sku: nil); end

  sig { void }
  def clear_quantity; end

  sig { void }
  def clear_sku; end

  sig { returns(Integer) }
  def quantity; end

  sig { params(value: Integer).void }
  def quantity=(value); end

  sig { returns(String) }
  def sku; end

  sig { params(value: String).void }
  def sku=(value); end
end
