# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Order::V1::ReturnStatus`.
# Please instead update this file by running `bin/tapioca dsl Order::V1::ReturnStatus`.


module Order::V1::ReturnStatus
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Order::V1::ReturnStatus::RETURN_STATUS_GOODS_RECEIVED = 2
Order::V1::ReturnStatus::RETURN_STATUS_OPEN = 1
Order::V1::ReturnStatus::RETURN_STATUS_REJECTED = 4
Order::V1::ReturnStatus::RETURN_STATUS_RESOLVED = 3
Order::V1::ReturnStatus::RETURN_STATUS_UNSPECIFIED = 0
